#!/bin/bash

run() {
    docker compose run --rm -it \
        $1 \
        "${@:2}"
}

if [ "$1" == "bootstrap" ]
    then
        ./scripts/bootstrap.sh
    exit
fi

if [ "$1" == "start" ]
    then
        ./scripts/start.sh $2
    exit
fi

if [ "$1" == "stop" ]
    then
        ./scripts/stop.sh
    exit
fi

if [ "$1" == "restart" ]
    then
        ./scripts/restart.sh $2
    exit
fi

if [ "$1" == "test" ]
    then
        args="${@:2}"
        run cli ./vendor/bin/pest "$args"
    exit
fi

if [ "$1" == "testf" ]
    then
        ./cli test --filter="'${*:2}'"
    exit
fi

if [ "$1" == "testg" ]
    then
        ./cli test --group="'${*:2}'"
    exit
fi

if [ "$1" == "format" ]
    then
        ./cli ./vendor/bin/pint ${@:2}
    exit
fi

if [ "$1" == "analyze" ]
    then
        ./cli ./vendor/bin/phpstan analyse ${@:2}
    exit
fi

if [ "$1" == "bun" ]
    then
        run bun "$@"
    exit
fi

run cli "$@"